### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ozak** [dharhas/smear#1]
@dharhas Is there an example of usage of this package? Is it superseded by some other package? 

Thanks

**Comment by dharhas** [comment]
This is not really a finished package. I developed the original version at my previous company and was in the process of untangling the algorithms from company specific internal code so that they could be open sourced. The main pieces are in place now but I haven't worked on this in 2 years. There is an example of using the kdtree inverse distance weighting method in the examples folder, but if you want an example of how to put the algorithms together to do an anisotropic interpolation, no examples exist, although I think all the pieces are there.

**Comment by ozak** [comment]
Thanks!
